version: "3.8"
services:
  api:
    build: .
    container_name: pulseops_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://pulseuser:pulsepass@postgres:5432/pulsedb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    restart: always
  worker:
    build: .
    container_name: pulseops_celery_worker
    command: celery -A app.workers.celery_app.celery_app worker --loglevel=info
    environment:
      - DATABASE_URL=postgresql://pulseuser:pulsepass@postgres:5432/pulsedb
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis
    restart: always
  postgres:
    image: postgres:16-alpine
    container_name: pulseops_postgres
    environment:
      POSTGRES_USER: pulseuser
      POSTGRES_PASSWORD: pulsepass
      POSTGRES_DB: pulsedb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: pulseops_redis
    ports:
      - "6379:6379"
volumes:
  postgres_data:
